### ISSUE TITLE
[Q] How to handle a merge conflict on pu

### ISSUE THREAD

**Issue by webstacker** [rocketraman/gitworkflow#2]
What's the best way of doing this and having the fix in the topic branch?

**Comment by rocketraman** [comment]
Thanks @webstacker for raising this. There should definitely be discussion of this in both the [Concepts Summary](https://github.com/rocketraman/gitworkflow/blob/master/docs/concepts-summary.adoc) and [Task-Oriented Primer](https://github.com/rocketraman/gitworkflow/blob/master/docs/task-oriented-primer.adoc).

The git.git project sometimes handles this a bit differently, but the way I handle this is basically to first decide if the conflict is trivial or semantic. If it is trivial, I do the conflict resolution directly on `pu`. Then, `git-rerere` will generally [2] apply the same resolution automatically when merging the same topic to `next` or to `master`.

If the conflict is semantic or non-trivial, then that should be represented as a topic-dependency relationship. In other words, we determine from the conflict which other topic branch has conflicting work. Then, we encode that dependency by merging one topic into the other. For example:

1. Assume topic A conflicts with topic B.
2. We decide that topic B should depend on topic A.
3. On topic B, we do `git merge topic-B` [1]. If the merge is the first commit on the topic, remember to use `--no-ff` so the merge commit / dependency relationship is explicit. Resolve conflicts as necessary.

Now that topic B merges topic A, topic A and B can be merged into integration branches like `pu` with no conflicts, since the conflict resolution has already happened on the topic branch.

[1] This can also be handled as an interactive rebase e.g. rewind, merge topic-B, and rebuild topic on top.

[2] Rerere has [some limitations](https://public-inbox.org/git/17c46229-3b64-34f1-30fa-d40b77e1c054@gmail.com/) to be aware of, which makes it even more important to ensure that only trivial conflicts are handled this way.

**Comment by webstacker** [comment]
Thanks @rocketraman for the explanation. Also, thanks for the [great article](https://hackernoon.com/how-the-creators-of-git-do-branches-e6fcc57270fb)

It would be good to have as few rules as possible to implement this workflow. Given the limitations you noted around rerere, do you think it's worth treating **all** conflicts in a consistent manner, by using the topic merging strategy?

Are you able to provide more info on how the [blameconflict](https://gist.github.com/rocketraman/1fdc93feb30aa00f6f3a9d7d732102a9#file-gitconfig-L81) alias can help with identifying what **topics** conflict on pu? I've had a look, but it outputs the name of the topic that is being merged and HEAD.

**Comment by rocketraman** [comment]
@webstacker :

> It would be good to have as few rules as possible to implement this workflow. Given the limitations you noted around rerere, do you think it's worth treating all conflicts in a consistent manner, by using the topic merging strategy?

I personally don't think having such hard and fast rules is a good idea -- I'd rather promote understanding and flexibility. Also, I think this will result in unnecessary topic merges/dependencies. If topic A depends on topic B, then topic B will always be deployed with topic A. If the only reason A depends on B is a trivial conflict, then you are unnecessarily limiting your flexibility to merge a subset of topics into more stable integration branches. Lastly, git rerere has no problem with trivial conflicts, and I see no reason not to use it for those cases, again, with an understanding of its limitations. 

> Are you able to provide more info on how the blameconflict alias can help with identifying what topics conflict on pu? I've had a look, but it outputs the name of the topic that is being merged and HEAD.

Hmm, can you try the alias again with `merge.conflictstyle = diff3` in your git config i.e. `git config --global merge.conflictstyle diff3`?

**Comment by webstacker** [comment]
I take your point about the unnecessary merges.

I added the conflictstyle config but I'm getting the same result. I'm maybe using it incorrectly?...

I setup a [test repo](https://github.com/webstacker/yogurt)

There are 3 topic branches. topic1 and topic2 have been merged in to pu. topic3 deliberately conflicts with topic1. When I merge topic3 in to pu I get the expected merge conflict. I then run:

`git blameconflict .env`

Which outputs:

```
00000000 (Not Committed Yet 2018-04-30 16:16:35 +0100 1) <<<<<<< HEAD
00000000 (Not Committed Yet 2018-04-30 16:16:35 +0100 2) SOME-VAR=SOME-VALUE
00000000 (Not Committed Yet 2018-04-30 16:16:35 +0100 3) ||||||| merged common ancestors
00000000 (Not Committed Yet 2018-04-30 16:16:35 +0100 4) =======
00000000 (Not Committed Yet 2018-04-30 16:16:35 +0100 5) SOME-OTHER-VAR=SOME-OTHER-VALUE
00000000 (Not Committed Yet 2018-04-30 16:16:35 +0100 6) >>>>>>> topic3
```

**Comment by rocketraman** [comment]
In your test repo, I wonder if its because `.env` was added in both branches, which is triggering an unhandled edge case in merge + blame? You do appear to be using it correctly.

If you have my [lg](https://gist.github.com/rocketraman/1fdc93feb30aa00f6f3a9d7d732102a9#file-gitconfig-L3) alias here is another way to figure out what is going on in this case:

`git lg --all -- .env`

which outputs:

```
* e6df800 Add .env file Stephen S (39 minutes ago)  (origin/topic3, topic3)
* c65e0e3 Add .env file Stephen S (43 minutes ago)  (origin/topic1)
```

**Comment by rocketraman** [comment]
@webstacker The conflict markers look exactly right given `.env` was added on both topics. Not sure why blame doesn't show the correct information, but for the most part things are working as expected. I'm going to go ahead and close this issue. Feel free to re-open if there are still open questions.
