### ISSUE TITLE
[Q] Why can't i merge next into master?

### ISSUE THREAD

**Issue by emahuni** [rocketraman/gitworkflow#5]
I remember you mentioning this in your tute, but you didn't explain why.

Ok, I have the four branches and I have created a topic and all went well. Then I went thru pu and then next processes. Did the same to other nine topics and eventually had 10 of them.

Now we want to cut a release after CI passes on next. If I got it right you said master and next never merge nor does pu and next nor pu and master. It means I have to merge those topic branches one by one into master, so why not just merge next into master seeing that is the state of the project we want to release? 

> This is similar in concept to GitFlow’s release branch, but far more flexible and powerful, since master has no dependencies on next whatsoever, nor is next ever merged wholesale into master (unlike the corresponding GitFlow branches develop and release).

The keyphrase here is:
>  **nor** is next **ever** merged ***wholesale*** into master

What's wrong with that since they all have a common ancestor?
Will something bad happen when we reset next and pu to master?
Is there a caveat in `git checkout master && git merge --no-ff next && git checkout next && git reset --hard master` approach, when the state of next branch is what we want to release?

**Comment by rocketraman** [comment]
@emahuni Yes, I would say the primary reason is to keep the `log --first-parent` history of `master` clean -- if you merge `next` into `master`, in order to find the specific topic branches merged, you will have to dig one level deeper than a simple `log --first-parent master` (you'd have to do that on the merge commit in turn i.e. `log --first-parent <merge-commit>`).

Merging the individual topics into `master` also gives you the option to skip merging one or more of them. However, it is not unusual to want to merge every topic in `next` into `master`. This is easily scripted:

```
# using `mergedinto` alias, this keeps the merge commit order, but removes dups i.e.
# merge A, merge B, then merge A, becomes merge A, B -- in my experience this works well
# https://gist.github.com/rocketraman/1fdc93feb30aa00f6f3a9d7d732102a9#file-gitconfig-L60
git mergedinto master..next > /tmp/branches

# fish shell syntax
while read x
  echo "Merging $x"
  # mb (merge-branch) is another alias I use to avoid having to pull all the topic branches down locally
  # but otherwise this is a simple `merge --no-ff`
  # https://gist.github.com/rocketraman/1fdc93feb30aa00f6f3a9d7d732102a9#file-gitconfig-L14
  git mb $x; or break
end < /tmp/branches
```

The subsequent command has to be run multiple times in case of intermediate conflict resolutions -- however it works well as a repeatable idempotent command (git reports "up-to-date" for branches already merged).

Another tip: if you were not the one to do all the merges into `next`, before running the command above, train your local rerere cache from `next` to repeat the same conflict resolutions when merging to master:

```
bash ~/source/git.git/contrib/rerere-train.sh -o master..next
```

This is the kind of thing for which we should add scripts into this repo, but I'd like them to soak and/or get feedback from people such as yourself before doing that. Let me know how it goes.
