### ISSUE TITLE
[Q] Create release is different from git.git

### ISSUE THREAD

**Issue by SevereOverfl0w** [rocketraman/gitworkflow#9]
I'm looking at implementing this, and comparing `man gitworkflows` with what is here.
I noticed that gitworkflows says:

https://git-scm.com/docs/gitworkflows#_maintenance_branch_management_after_a_feature_release

```

Recipe: Update maint to new release

    git checkout maint

    git merge --ff-only master

```

But https://github.com/rocketraman/gitworkflow/blob/c3cb27618e5fcd41dc96508c403b35de50a296cc/docs/task-oriented-primer.adoc#create-a-release create a release suggests instead:

```
$ git checkout maint
(maint) $ git reset --hard v2.7.0
(maint) $ git push --set-upstream origin +maint
```

Why the difference?

**Comment by rocketraman** [comment]
Good catch. The approach given in the workflows doc is correct, and this needs to be updated here. If you've done everything correctly i.e. merged any hot-fixes made in `maint` into master (as per the previous section in the man page), then the end result is exactly the same.

However, using `merge` with fast-forward performs a double-check that everything is good: it verifies that there were no hot-fixes in `maint` that will be lost if `maint` is reset to the latest `master`, because the "fast-forward" will only work if `master` is indeed a super-set of `maint`.

Thank you for catching this!

**Comment by rocketraman** [comment]
@SevereOverfl0w I committed an update, please review and let me know if that is now consistent with your understanding.

**Comment by SevereOverfl0w** [comment]
Does the push still need to --set-upstream now? But otherwise it looks like how I was expecting, yep!

**Comment by rocketraman** [comment]
@SevereOverfl0w Another good catch, updated in dc744821fd94cc8abb80f0187e64fc3683b63e0c.
